apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  creationTimestamp: null
  labels:
    app: model
  name: model
spec:
  revisionHistoryLimit: 5
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: model
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: model
    spec:
      containers:
      - env:
        - name: jdbc_url
          value: jdbc:postgresql://db:5432/
        image: modelix/modelix-model:0.0.34
        imagePullPolicy: IfNotPresent
        name: model
        ports:
        - containerPort: 28101
        - containerPort: 5071
          name: "jvm-debug"
        volumeMounts:
          - name: modelsecret
            mountPath: /secrets/modelsecret
            readOnly: true
        resources: 
          requests:
            memory: "1000Mi"
            cpu: "0.1"
          limits:
            memory: "1500Mi"
            cpu: "1.0"
        readinessProbe:
          httpGet:
            path: /health
            port: 28101
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 28101
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 10            
      restartPolicy: Always
      volumes:
        - name: modelsecret
          secret:
            secretName: modelsecret
status: {}
